###example
##import turtle
##candy=turtle.Turtle()
##candy.shape('classic')
##candy.color('blue')
##candy.write('What color am i now?')
##candy.left(45)
##candy.forward(100)
##
##candy.color('green')
##candy.write('What color am i now?')
##candy.left(45)
##candy.forward(100)
##
##candy.color('red')
##candy.write('What color am i now?')
##candy.left(45)
##candy.forward(100)
##
##candy.color('yellow')
##candy.write('What color am i now?')
##candy.left(45)
##candy.forward(100)
##
##candy.color('orange')
##candy.write('What color am i now?')
##candy.left(45)
##candy.forward(100)
##
##candy.color('purple')
##candy.write('What color am i now?')
##candy.left(45)
##candy.forward(100)
##
##candy.color('pink')
##candy.write('What color am i now?')
##candy.left(45)
##candy.forward(100)
##
##candy.color('black')
##candy.write('What color am i now?')
##candy.left(45)
##candy.forward(100)

#Your Turn

import turtle
dell=turtle.Turtle()
dell.shape('classic')
dell.pencolor('red')
dell.pensize(5)
dell.backward(100)
dell.left(90)
dell.forward(150)
dell.right(90)
dell.forward(100)
dell.backward(100)
dell.left(90)
dell.forward(150)
dell.right(90)
dell.forward(100)

dell.penup()
dell.right(90)
dell.forward(300)
dell.left(90)
dell.forward(50)
dell.pendown()

dell.pencolor('green')
dell.pensize(20)
dell.left(90)
dell.forward(150)
dell.right(90)
dell.forward(100)
dell.penup()
dell.right(90)
dell.forward(75)
dell.right(90)
dell.forward(20)
dell.pendown()
dell.forward(80)

dell.penup()
dell.backward(100)
dell.left(90)
dell.forward(75)
dell.left(90)
dell.forward(50)
dell.pendown()


dell.pencolor('dark blue')
dell.pensize(15)
dell.left(60)
dell.forward(100)
dell.right(120)
dell.forward(100)
dell.backward(50)
dell.right(120)
dell.forward(50)
