import turtle
cyber= turtle.Turtle()
cyber.shape('turtle')
cyber.color('green')
cyber.begin_fill()
cyber.circle(100)
cyber.end_fill()
cyber.penup()
cyber.forward(-50)
cyber.pendown()
cyber.color('red')
cyber.begin_fill()
cyber.circle(100)
cyber.end_fill()
cyber.penup()
cyber.forward(-50)
cyber.pendown()
cyber.color('yellow')
cyber.begin_fill()
cyber.circle(100)
cyber.end_fill()


cyber.penup()
cyber.forward(50)
cyber.right(90)
cyber.forward(50)
cyber.left(90)
cyber.color('blue')
cyber.pendown()
cyber.stamp()
cyber.penup()
cyber.right(90)
cyber.forward(50)
cyber.left(90)
cyber.forward(-50)
cyber.color('magenta')
cyber.write('Ultimate Coders!',"50 pt bold")
